### ISSUE TITLE
vite v3.1 not work

### ISSUE THREAD

**Issue by SvenWangChina** [Akryum/meteor-vite#13]
Vite v3.1 not work, get follow error

```
App.vue:7 Uncaught TypeError: Cannot read properties of undefined (reading 'accept')
    at App.vue:7:20
(anonymous) @ App.vue:7
```

**Comment by diavrank** [comment]
I have a working example here https://github.com/diavrank/theory-swe/pull/5 with Vite 4

**Comment by Akryum** [comment]
I upgraded the example to vite 4.1 and it works great
