### ISSUE TITLE
Comments in packages break parsing

### ISSUE THREAD

**Issue by red-meadow** [Akryum/meteor-vite#26]
Any comment with the word `"module"` in a package entry point breaks exports. It's probably caused by invalid parsing rules.

**How to reproduce**
1. In example project, add the comment `// module` anywhere in `test-modules/index.js`.
2. Check the output of `(vite) meteor/test:modules` in the console.
![image](https://user-images.githubusercontent.com/38740713/217385760-925b2497-20bb-4e5b-8b0d-6133b54c7343.png)

**Comment by JorgenVatle** [comment]
Turns out it's not only comments, but also filenames including "module". Seems to be a Meteor thing though, as the generated package sources appear to change from e.g. `module.link(...)` to `module1.link(...)`.
