### ISSUE TITLE
Missing meteor.clientEntry error on Windows

### ISSUE THREAD

**Issue by dispbd** [Akryum/meteor-vite#4]
Hello. At first I thought the problem was in my code. But it turned out that the Vue example throws the same error:
![error](https://i.vgy.me/yy8xKV.png)

**Comment by Akryum** [comment]
Probably a Windows issue

**Comment by Akryum** [comment]
Fixed in v0.1.7

**Comment by dispbd** [comment]
Great! Thank you!!!
